### ISSUE TITLE
What's causing this error?

### ISSUE THREAD

**Issue by ssamjh** [ExtendedAlpha/SeparateWorldItems#10]
http://pastebin.com/Q31euyMy

**Comment by TriptychPlaysMC** [comment]
My best guess is that your default settings.json got corrupted you will need to delete it and restart your server.

**Comment by sgdc3** [comment]
I think we need a proper message when there is a configuration error, for example <red><bold>Error: invalid syntax in groups.yml! Try deleting it and restart your server!

**Comment by sgdc3** [comment]
If the problem is resolved, please close the issue. Thanks :)

**Comment by TriptychPlaysMC** [comment]
User has contacted me on spigot issue now fix closed.
