### ISSUE TITLE
Rename settings.json to a more suitable name

### ISSUE THREAD

**Issue by sgdc3** [ExtendedAlpha/SeparateWorldItems#18]

**Comment by TriptychPlaysMC** [comment]
What do you think it should be renamed to?

**Comment by sgdc3** [comment]
sampleplayerdata.json

**Comment by TriptychPlaysMC** [comment]
Ok i'll do that really fast.

**Comment by sgdc3** [comment]
Do you have any instant chat that we could use to discuss? ;)

**Comment by TriptychPlaysMC** [comment]
Skype or hipchat will work and if you have slack that will also work.

**Comment by sgdc3** [comment]
Ok skype is ok, what's your nickname?

**Comment by TriptychPlaysMC** [comment]
It's triptychplaysgames

**Comment by sgdc3** [comment]
Contact request sent :)

**Comment by TriptychPlaysMC** [comment]
Added

**Comment by hockeymikey** [comment]
Could you guys add me?  Would be quicker to communicate between us (username is hockeymikey)
