### ISSUE TITLE
We should update JSON library or use instead GSON

### ISSUE THREAD

**Issue by sgdc3** [ExtendedAlpha/SeparateWorldItems#19]

**Comment by TriptychPlaysMC** [comment]
That's what I been thinking as well. I think the best route will be to change to GJSON.

**Comment by sgdc3** [comment]
I remember GSON is already implemented in the Bukkit API, right?

**Comment by TriptychPlaysMC** [comment]
Yeah it is i think.

**Comment by hockeymikey** [comment]
I believe GSON moved locations at some point in 1.8.* so we'll have to note that to ensure that SWI is backwards compatible.

**Comment by sgdc3** [comment]
We resolved the problem by including gson into maven dependencies.

**Comment by sgdc3** [comment]
Sorry, i forgot that for now we still use JSON, Triptych will replace it with GSON in the future.

**Comment by TriptychPlaysMC** [comment]
GSON will be added once i figure out how to rewrite the separatorlib and not break the plugin.

**Comment by TriptychPlaysMC** [comment]
Closing this for now
