### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by AssassinsCreepZ** [ExtendedAlpha/SeparateWorldItems#22]
Hey,

I'm searching for so long for a plugin like this. It works. Everything is fine and there are no bugs. Except that it's only for op's. I don't know why but when I change something in the config, it just is useful for Operators. Normal players won't get a new Inventory per world. Also the grouping of worlds isn't possible even of op's for me. I tried really everything. Here are my plugins:
limit:
  WorldEdit: []
  MotdManager: []
  MassiveCore: []
  Vault: []
  Poke: []
  LongerTimev1: []
  Multiverse-Core: []
  PermissionsEx: []
  WorldGuard: []
  ColoredTablist: []
  dynmap: []
  AutoMessage: []
  PVPLEVELS:
  PvPControl:
  Shopkeepers:
  CommandEdit: []
  ChestCommands: []
  Lockette: []
  GriefPrevention: []
  mcMMO: []
  Heroes:
  VoidWorld: []
  Essentials: []
  CommandSigns: []
  EssentialsProtect: []
  EssentialsSpawn: []
  Multiverse-NetherPortals: []
  MoreSounds: []
  Dynmap-GriefPrevention: []
  EchoPet: []
  MythicMobs:
  ChestShop: []
  EssentialsChat: []
  Factions:
  Statistics: []
  AutoRestart: []
  ProtocolLib: []
  HideAndCustomPlugins: []
  TitleManager: []
  Trading:
  PlayTimeRewardsRecoded:
  SeparateWorldItems: []

(out of the config of PerWorldPlugins)

If u need more to help me just tell my what. I just don't know what to do :(

**Comment by hockeymikey** [comment]
Sounds like an issue with another plugin.  Try disabling them, one by one until you find it.
Or depending on your permissions plugin enable debugging and see what perm node is being called that is given to the ops.

Also what version are you using for spigot and SWI?

**Comment by sgdc3** [comment]
I think it's a problem with PerWorldPlugins, it's an hacky plugin which breaks everything!

**Comment by AssassinsCreepZ** [comment]
Well the pwp config doesn't change anything within swi. It's enabled in all worlds, but I can disable it and try

**Comment by sgdc3** [comment]
Yes but probably the fact PWP is enabled and spread its hacky functions break some of the SWI events.

**Comment by AssassinsCreepZ** [comment]
Never had such problems... Even if it's PWP. What other plugin should I use? I need one to disable certain plugins in certain worlds :/

**Comment by sgdc3** [comment]
An example?

**Comment by sgdc3** [comment]
Of plugin which must be disabled in certain worlds I mean.

**Comment by AssassinsCreepZ** [comment]
I have a RPG World and a normal player world. There have to be two different inventories because they get special items in the RPG world. Also in the RPG world are some plugins like pvplevels which formats the chat in that world or factions. They cannot be enabled in the normal player world. That would destroy the sense of the RPG world. If you take a look at PWPs spigot page it seems like it cannot be it's fault. What I wonder about is that I changed from GroupManager to PEX, from Multiverse Inventorys to Multiinv to SeperatWorldInventories to SeperatWorldItems, but it's all the time the same error. Grouping and normal player right won't work...

**Comment by AssassinsCreepZ** [comment]
Oh yeah forget to say it, swi is the newest version and spigot is 1.8.1. Shouldn't break anything should it?

**Comment by AssassinsCreepZ** [comment]
Nope it's not an issue due to pwp.

**Comment by TriptychPlaysMC** [comment]
Hello AssassinCreepZ.
Would you try disabling every plugin one by one. As this can't be a problem with SWI as there's no permission to exempt you from changing inventories when changing worlds.

**Comment by TriptychPlaysMC** [comment]
Closing issue due to no response.
