### ISSUE TITLE
Item loss with gamemode 2&3

### ISSUE THREAD

**Issue by ZPinka** [ExtendedAlpha/SeparateWorldItems#25]
It seems that OPs are loosing their stuff when changing their gamemode to 2 or 3. Server is 1.8.6.

**Comment by sgdc3** [comment]
Only Op or also people with '*' node?

**Comment by ZPinka** [comment]
People with * perms.

**Comment by hockeymikey** [comment]
There's your problem, don't use the '*' node.

**Comment by ZPinka** [comment]
Okay, one question: is this issue only when you dont give negative perms for this plugin (eg: i just remove a few permissions from * perms) or can it be that other plugins can cause this issue? I am about to just give negative perms to the * user

**Comment by sgdc3** [comment]
@hockeymikey If this is the problem, it's a bug and we should fix it!

**Comment by TriptychPlaysMC** [comment]
@ZPinka this is normally caused by your permissions plugin or one that handles permissions. But this is also a problem on our part, expect an update soon fixing this.
