### ISSUE TITLE
Per Gamemode Inventory Will Not Turn off.

### ISSUE THREAD

**Issue by RustyDagger** [ExtendedAlpha/SeparateWorldItems#32]
You can see from the Logfile below exactly what i did. Changing gamemode both with /gm and with a map change is breaking some part of Item code.
I am pleased to NOTE that item names ARE SAVING.
I still can not get per gamemode inventories to turn off. Its stuck enabled ignoring the config,

http://pastebin.com/rbw3t5H7

**Comment by RustyDagger** [comment]
The errors seem to of stopped, All on their own. I think it may of just been the Old data that it had to update when the name saving was fixed.

The only issue that remains is it not letting me turn off Per Gamemode Inventories Unless its another plugin doing it. I some how doubt that :?

**Comment by sgdc3** [comment]
Please rename the issue title, we'll investigate on this issue ;)

**Comment by RustyDagger** [comment]
I just found more that is broken with Per Gamemode Inventories.

If you Are on a survival world and use /Gm to change to creative.
Put some Items ( or Have an empty Inventory. )
Then Logout of the server
Then Login. 
The Plugin wipes your survival inventory and replaces it with the creative inventory you had when you logged out.

I really dont understand per gamemode inventories. If you dont trust staff they should not be staff and even with the seperate you just drop items and pick them up or use a chest its like half a feature that really does nothing.

**Comment by TriptychPlaysMC** [comment]
I'm going to remove separate gamemode inventories latter today until I can fix it.

**Comment by sgdc3** [comment]
In my opinion separate gamemodes should be a SWC function. (Per gamemode inventory should be an hook of SWI with SWC)

**Comment by TriptychPlaysMC** [comment]
That's not a bad idea I hope to get that all started soon.

**Comment by TriptychPlaysMC** [comment]
This now has be removed https://github.com/ExtendedAlpha/SeparateWorldItems/commit/f99548b15d2ca27bfb86e81c59f103b02b8af6f5
