### ISSUE TITLE
Something went wrong logging an Inventory event - PlayerChangedWorldEvent

### ISSUE THREAD

**Issue by CoderInOrbit** [ExtendedAlpha/SeparateWorldItems#36]
Hello,

I'm having trouble using SWI. Whenever I warp somewhere, the inventory remains the same, and I'm getting this error : 

07.06 19:07:52 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
07.06 19:07:52 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
07.06 19:07:52 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
07.06 19:07:52 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
07.06 19:07:52 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
07.06 19:07:52 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
07.06 19:07:52 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
07.06 19:07:52 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
07.06 19:07:52 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
07.06 19:07:52 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) [CraftServer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
07.06 19:07:52 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
07.06 19:07:52 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
07.06 19:07:52 [Server] INFO at com.earth2me.essentials.Essentials.onCommand(Essentials.java:380) [Essentials.jar:?]
07.06 19:07:52 [Server] INFO at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:505) [Essentials.jar:?]
07.06 19:07:52 [Server] INFO at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:149) [Essentials.jar:?]
07.06 19:07:52 [Server] INFO at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:51) [Essentials.jar:?]
07.06 19:07:52 [Server] INFO at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.java:130) [Essentials.jar:?]
07.06 19:07:52 [Server] INFO at com.earth2me.essentials.Teleport.warp(Teleport.java:259) [Essentials.jar:?]
07.06 19:07:52 [Server] INFO at com.earth2me.essentials.Teleport.teleport(Teleport.java:194) [Essentials.jar:?]
07.06 19:07:52 [Server] INFO at com.earth2me.essentials.Teleport.now(Teleport.java:113) [Essentials.jar:?]
07.06 19:07:52 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.teleport(CraftPlayer.java:506) [CraftPlayer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
07.06 19:07:52 [Server] INFO at net.minecraft.server.management.ServerConfigurationManager.respawnPlayer(ServerConfigurationManager.java:810) [oi.class:?]
07.06 19:07:52 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.firePlayerChangedDimensionEvent(FMLCommonHandler.java:562) [FMLCommonHandler.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
07.06 19:07:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
07.06 19:07:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
07.06 19:07:52 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
07.06 19:07:52 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
07.06 19:07:52 [Server] INFO org.bukkit.event.EventException
07.06 19:07:52 [Server] ERROR Could not pass event PlayerChangedWorldEvent to SeparateWorldItems v2.9.0
07.06 19:07:48 [Server] INFO Something went wrong logging an Inventory event

Thank you kindly

**Comment by sgdc3** [comment]
Try latest dev build here: http://ci.md-5.net/job/SeparateWorldItems/

**Comment by CoderInOrbit** [comment]
Awesome sorry about such a simple issue !

Just a tiny thing, is it possible to split the Baubles inventory between worlds too ? My players have separate inventories, but they keep their Baubles items across though

**Comment by sgdc3** [comment]
@TriptychPlaysMC I think SWI haven't mod support yet...

**Comment by CoderInOrbit** [comment]
Ok, that would also explain why their bags were getting wiped too. Thank you for the help !
