### ISSUE TITLE
We need a new way to provide a MultiInv maven repository.

### ISSUE THREAD

**Issue by sgdc3** [ExtendedAlpha/SeparateWorldItems#8]
The actual method is very bugged!

**Comment by TriptychPlaysMC** [comment]
Yeah i've been looking for a public repo but i can't find one anywhere. I have another way to do it but it has to be done by using bitbucket it's kinda the save method.

**Comment by sgdc3** [comment]
And also how jenkins obtain craftbukkit from maven if it was removed? :/

**Comment by sgdc3** [comment]
On my pc I can't obtain craftbukkit from maven.

**Comment by TriptychPlaysMC** [comment]
That's a bit weird i'll see if spigot nexus server is down really fast cause that's how i been obtaining craftbukkit.

**Comment by sgdc3** [comment]
I think they removed it today :(

**Comment by TriptychPlaysMC** [comment]
Yeah thay did just remove it from the pox.xml and you should be good.

**Comment by sgdc3** [comment]
It can't compile...

**Comment by TriptychPlaysMC** [comment]
Let me see i'll clone it to my pc really fast and test it.

**Comment by sgdc3** [comment]
Also with spigotapi instead of bukkit i can't compile.

**Comment by TriptychPlaysMC** [comment]
This is the only error i'm getting when i try to compile out.

[ERROR] location: class com.ExtendedAlpha.SWI.SeparatorLib.SingleItemSeparator
[ERROR] /C:/Users/User/Desktop/SeparateWorldItems/src/main/java/com/ExtendedAlph
a/SWI/SeparatorLib/SingleItemSeparator.java:[74,41] cannot find symbol
[ERROR] symbol:   variable stuff

**Comment by sgdc3** [comment]
Yes it can't find what "item" and "stuff" means (They are included in craftbukkit/spigot)

**Comment by TriptychPlaysMC** [comment]
Ok give me a few minutes i'm going to go eat then i'll try to find out what it is.

**Comment by TriptychPlaysMC** [comment]
Ok never mind it was an easy fix all it is i stuff and item is a local variable i created awhile back and it's used feather down in the class. just replace the SingleItemSeparator class with this one.
http://hastebin.com/ahikasajob.coffee

**Comment by sgdc3** [comment]
It's my version with 1.7 fix?

**Comment by TriptychPlaysMC** [comment]
I'm testing right now if it does just re-open the pull request and i'll push it. Also i was wondering if you want to join the developer team?

**Comment by sgdc3** [comment]
I'm a C ++ programmer, I don't know Java very well, but I can help in many other ways though ;)

**Comment by TriptychPlaysMC** [comment]
Alright.

**Comment by sgdc3** [comment]
MultiInv Repository just corrupted all my mavel local folder xD

**Comment by sgdc3** [comment]
Maybe it's better to split the plugin into two parts: Converter and Core

**Comment by TriptychPlaysMC** [comment]
Yeah that would be cool.

**Comment by sgdc3** [comment]
Can you quickly remove converters from the plugin? I can't compile with MultiInv!

**Comment by TriptychPlaysMC** [comment]
You can add a local jar file it would be easier then removing the converters.

**Comment by sgdc3** [comment]
It's true but i'm a lover of maven... xD

**Comment by TriptychPlaysMC** [comment]
As am I. I'll have to find a way to do it without breaking the plugin.

**Comment by TriptychPlaysMC** [comment]
Hmm for some reason i'm still getting the error when i'm using 1.7. I'm going to try to apply a different method really fast to see if that will work.

**Comment by sgdc3** [comment]
It still want craftbukkit!

**Comment by TriptychPlaysMC** [comment]
Yeah!! Ok i fixed it you can now re-open the pull request after you apply this patch in the SingleItemSeparator.
http://hastebin.com/zexahakifa.coffee

I also made a slight change in the pom,xml there what a duplicate bukkit in there.
http://hastebin.com/benowofejo.xml

**Comment by sgdc3** [comment]
How do you fixed it?

**Comment by sgdc3** [comment]
Ok it compiles but need testing!

**Comment by sgdc3** [comment]
Pull request sent!

**Comment by sgdc3** [comment]
I hope jenkins will compile it correctly!

**Comment by TriptychPlaysMC** [comment]
It will!

**Comment by TriptychPlaysMC** [comment]
And it's good!
http://ci.md-5.net/job/SeparateWorldItems/17/

**Comment by sgdc3** [comment]
YEAH!

**Comment by sgdc3** [comment]
We need some beta testers xD

**Comment by TriptychPlaysMC** [comment]
Yeah i already posted it on spigot for some people to test.

**Comment by sgdc3** [comment]
Why we don't use circle ci instead of md5 jenkins?

**Comment by sgdc3** [comment]
circle ci it's free and have more functions

**Comment by TriptychPlaysMC** [comment]
Main reason is people need to have an account to download stuff. But I'll look into it to see if there's a way to change it.
